"""Add affiliation to User model

Revision ID: 0730c08a761b
Revises: af20813cab10
Create Date: 2025-11-14 16:01:45.415592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0730c08a761b'
down_revision = 'af20813cab10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('program')
        batch_op.drop_column('user_class')
        batch_op.drop_column('category')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
