"""Add finance and todo tables

Revision ID: 4eddae9245c9
Revises: c3e6e1ec7672
Create Date: 2025-11-28 00:41:46.972638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eddae9245c9'
down_revision = 'c3e6e1ec7672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finance_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('to_do_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_to_do_item_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_to_do_item_timestamp'))

    op.drop_table('to_do_item')
    with op.batch_alter_table('finance_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_log_timestamp'))

    op.drop_table('finance_log')
    # ### end Alembic commands ###
