"""Add has_seen_guide to User

Revision ID: 59a5a5010373
Revises: 8d0301e0465e
Create Date: 2025-11-29 00:43:22.418167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a5a5010373'
down_revision = '8d0301e0465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seen_guide', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_seen_guide')

    # ### end Alembic commands ###
