"""empty message

Revision ID: 829922c2d390
Revises: 10f1b598aa92
Create Date: 2025-08-14 19:01:40.733164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829922c2d390'
down_revision = '10f1b598aa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('bookmark_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookmark_post_id_fkey'), 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
