"""Resync

Revision ID: 848fc471f2e4
Revises: 
Create Date: 2025-11-24 23:08:04.098952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848fc471f2e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # likeテーブルの作成だけを残す
    op.create_table('like',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'post_id', name='_user_post_like_uc')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
