"""Add GourmetSpot model

Revision ID: 889209de3135
Revises: e92443df6746
Create Date: 2025-12-05 22:10:32.865269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889209de3135'
down_revision = 'e92443df6746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gourmet_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_editor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_editor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gourmet_spot')
    # ### end Alembic commands ###
