"""Add finance and todo tables

Revision ID: 8d0301e0465e
Revises: ccc9224730ec
Create Date: 2025-11-28 01:52:12.998158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0301e0465e'
down_revision = 'ccc9224730ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('to_do_item', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
