"""Add dark_mode column to User

Revision ID: abf7081a2a16
Revises: 
Create Date: 2025-11-18 00:23:19.063069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf7081a2a16'
# revision identifiers, used by Alembic.
revision = 'abf7081a2a16'
down_revision = '21dbbc274d99' # <-- 'None' から '21dbbc274d99' に変更
branch_labels = None
depends_on = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
