"""Add push_notifications_enabled to User

Revision ID: baf71f9983d8
Revises: bdbd87084b20
Create Date: 2025-11-16 21:54:38.801196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf71f9983d8'
down_revision = 'bdbd87084b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_notifications_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_notifications_enabled')

    # ### end Alembic commands ###
